/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "memoriesTable-dev",
            "region": "eu-west-1"
        },
        {
            "tableName": "condolencesTable-dev",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "digital-memorial-media26d34-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:c4ef7bb9-9276-4d32-9037-ed19a9bddcee",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_X9lcPIvOe",
    "aws_user_pools_web_client_id": "6mcvha75lcedqv48phhfgnv41t",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "memorialAPI",
            "endpoint": "https://kafcz1kbt2.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
